### ISSUE TITLE
Homeassistant 2022.2: cannot import name 'MediaPlayerDevice'

### ISSUE THREAD

**Issue by zwartevogel** [Imperial-Guard/Marantz_USB-Serial#4]
Since the installation of 2022.2(.2) the marantz USB serial plugin isn't working anymore. I'm using the serial connection to my Marantz (not the TCP version). It worked in the 2021.12 release. Error in de the log: 

Logger: homeassistant.config
Source: custom_components/marantzusb/media_player.py:11
Integration: marantzusb ([documentation](https://github.com/Imperial-Guard/marantz_tcp))
First occurred: 10:44:55 AM (1 occurrences)
Last logged: 10:44:55 AM
Platform error: media_player

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 583, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/marantzusb/media_player.py", line 11, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'MediaPlayerDevice' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)
